<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= BASE_URL . "/css/style.css" ?>">
    <title>Valorant Agents</title>
</head>

<body>

    <header>
        <nav>
            <a href="<?= BASE_URL ?>"><img class="homeIcon" src="resources/homeIcon.jpg" alt="Icono del home"></a>
            <a href="<?= BASE_URL ?>roles">Roles</a>
            <a href="<?= BASE_URL ?>administracion-agentes">Administración Agentes</a>
            <a href="<?= BASE_URL ?>administracion-roles">Administración Roles</a>
            <a href="<?= BASE_URL ?>iniciar-sesion">Iniciar sesión</a>
            <a href="<?= BASE_URL ?>cerrar-sesion">Cerrar sesión</a>

        </nav>
    </header>

    <main>